# validate.yml
# Validates that Libation will build on a pull request or push to master. 
---
name: validate

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      project_file: ./AudibleApi/AudibleApi.csproj
      nuspec_file: ./AudibleApi.nuspec
    secrets:
      nuget_token: ${{ secrets.NUGET_API_KEY }}
